
networks:
  openfga:

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    networks:
      - openfga
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - openfga_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
    networks:
      - openfga

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
    command: run
    networks:
      - openfga
    ports:
      # Needed for the http server
      - "8080:8080"
      # Needed for the grpc server (if used)
      - "8081:8081"

      - "3000:3000"
  
  opendoc-db:
    image: postgres:16.2
    container_name: postgres-app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=opendoc
      - POSTGRES_PASSWORD=opendocpass
      - POSTGRES_DB=opendocdb
    volumes:
      - opendoc_pgdata:/var/lib/postgresql/data
volumes:
  opendoc_pgdata:
  openfga_pgdata: